# API 相关设置
api:
  # 你的 OpenAI API key，用于身份验证
  # 获取 API key 的方法：访问 //platform.openai.com/account/api-keys 并创建一个新的 API key
  key: "your_openai_api_key"
  # OpenAI API 的基础 URL，用于构建请求
  base_url: "https://api.openai.com/v1"
# 支持的模型列表
models:
  # OpenAI ChatGPT
  - "gpt-3.5-turbo"
  - "gpt-4"
# 默认使用的模型
default_model: "gpt-3.5-turbo"
# 消息相关设置
messages:
  reload: "已重新加载配置文件！"
  help: "===== MineChatGPT 帮助 ====="
  help_ask: "/chatgpt <text> - 向ChatGPT提问"
  help_reload: "/chatgpt reload - 重新加载配置文件"
  help_model: "/chatgpt model <model_name> - 切换至其他模型"
  help_modellist: "/chatgpt modellist - 可用的模型列表"
  usage: "输入： /chatgpt model <model_name>"
  model_switch: "已切换至模型 %s"
  chatgpt_error: "无法联系ChatGPT。"
  chatgpt_response: "ChatGPT: %s"
  question: "你: %s"
  invalid_model: "模型无效。使用 /chatgpt modellist 查看可用模型。"
  available_models: "可用模型列表："
  no_permission: "你没有权限使用这个指令。需要的权限：%s"