# OpenAI API key setting
api:
  # Your OpenAI API key, used for authentication
  # To obtain an API key, visit https://platform.openai.com/account/api-keys and create a new API key
  key: "sk-your_openai_api_key"
  # The base URL for the OpenAI API, used to construct requests
  base_url: "https://api.openai.com/v1"
# List of supported models
models:
  # OpenAI ChatGPT
  - "gpt-3.5-turbo"
  - "gpt-3.5-turbo-instruct"
  - "gpt-4"
  - "gpt-4-turbo"
  - "gpt-4-turbo-preview"
  - "gpt-4o"
  - "gpt-4o-mini"
  # Google Gemini
  # - "gemini-pro"
  # - "gemini-1.5-pro"
  # Anthropic Claude
  # - "claude-3-opus"
  # - "claude-3-5-sonnet"
  # And more...
# The default model to use
default_model: "gpt-3.5-turbo"
# Conversation setting
conversation:
  # Continuous conversation switch
  context_enabled: false
  # Maximum number of historical records retained
  max_history_size: 10
# Characters setting
characters:
  # Format:
  # Character Name: "Character Prompt"
  ChatGPT: "You are a helpful assistant."
# Message settings
messages:
  reload: "&aConfiguration reloaded successfully!"
  clear: "&aConversation history has been cleared!"
  help: "&e===== MineChatGPT Help ====="
  help_ask: "&e/chatgpt <text> - Ask ChatGPT a question."
  help_reload: "&e/chatgpt reload - Reload the configuration file."
  help_model: "&e/chatgpt model <model_name> - Switch to a different model."
  help_modellist: "&e/chatgpt modellist - List available models."
  help_context: "&e/chatgpt context - Toggle context mode."
  help_clear: "&e/chatgpt clear - Clear conversation history."
  help_character: "&e/chatgpt character [character_name] - List or switch to a character."
  context_toggle: "&eContext is now %s."
  context_toggle_enabled: "&aenabled"
  context_toggle_disabled: "&cdisabled"
  current_model_info: "&eCurrent model: %s. Use /chatgpt model <model_name> to switch models."
  model_switch: "&aModel switched to %s"
  chatgpt_error: "&cFailed to contact ChatGPT."
  chatgpt_response: "&b%s: %s"
  question: "&bYou: %s"
  character_switched: "&aSwitched to character: %s"
  available_characters: "&eAvailable characters:"
  invalid_character: "&cInvalid character. Use /chatgpt character to list available characters."
  invalid_model: "&cInvalid model. Use /chatgpt modellist to see available models."
  available_models: "&eAvailable models:"
  no_permission: "&cYou do not have permission to use this command. Required permission: %s"
# If you don't know what this is, don't change it
debug: false