# API 相关设置
api:
  # 你的 OpenAI API key，用于身份验证
  # 获取 API key 的方法：访问 https://platform.openai.com/account/api-keys 并创建一个新的 API key
  key: "sk-your_openai_api_key"
  # OpenAI API 的基础 URL，用于构建请求
  base_url: "https://api.openai.com/v1"
# 支持的模型列表
models:
  # OpenAI ChatGPT
  - "gpt-3.5-turbo"
  - "gpt-3.5-turbo-instruct"
  - "gpt-4"
  - "gpt-4-turbo"
  - "gpt-4-turbo-preview"
  - "gpt-4o"
  # Google Gemini
  # - "gemini-pro"
  # - "gemini-1.5-pro"
  # Anthropic Claude
  # - "claude-3-opus"
  # - "claude-3-5-sonnet"
  # 以及更多...
# 默认使用的模型
default_model: "gpt-3.5-turbo"
conversation:
  max_history_size: 10
  context_enabled: false
# 消息相关设置
messages:
  reload: "&a已重新加载配置文件！"
  clear: "&a对话历史已清空！"
  help: "&e===== MineChatGPT 帮助 ====="
  help_ask: "&e/chatgpt <text> - 向ChatGPT提问"
  help_reload: "&e/chatgpt reload - 重新加载配置文件"
  help_model: "&e/chatgpt model <model_name> - 切换至其他模型"
  help_modellist: "&e/chatgpt modellist - 可用的模型列表"
  help_context: "&e/chatgpt context - 切换连续对话模式"
  help_clear: "/chatgpt clear - 清空对话历史"
  context_toggle: "&a连续对话模式已%s。"
  context_toggle_enabled: "开启"
  context_toggle_disabled: "关闭"
  current_model_info: "&e当前模型：%s，输入 /chatgpt model <model_name> 来切换模型。"
  model_switch: "&a已切换至模型 %s"
  chatgpt_error: "&c无法联系ChatGPT。"
  chatgpt_response: "&bChatGPT: %s"
  question: "&b你: %s"
  invalid_model: "&c模型无效。使用 /chatgpt modellist 查看可用模型。"
  available_models: "&e可用模型列表："
  no_permission: "&c你没有权限使用这个指令。需要的权限：%s"
# 如果你不知道这是什么，请不要动
debug: false
# 不要动！！！！！
version: 2.2